# Generated by Django 6.0.3 on 2026-03-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, choices=[('brand-peach', 'Random Thoughts'), ('brand-cream', 'School'), ('brand-teal', 'Personal')], max_length=50, null=True),
        ),
    ]
