# Generated by Django 6.0.3 on 2026-03-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_add_category_to_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('brand-peach', 'Random Thoughts'), ('brand-cream', 'School'), ('brand-teal', 'Personal')], default='brand-peach', max_length=50),
            preserve_default=False,
        ),
    ]
